name: my_first_app
description: A new Flutter project

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.4
  video_player: ^2.5.1
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5


flutter:
  uses-material-design: true
  assets:
    - assets/data.json


