// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWw10Ql1PQNBleeY4hcDrQc9nrlQ68Zwg',
    appId: '1:475073115193:web:316c90d8fad65b12acc9e8',
    messagingSenderId: '475073115193',
    projectId: 'sih-learning-platform',
    authDomain: 'sih-learning-platform.firebaseapp.com',
    storageBucket: 'sih-learning-platform.firebasestorage.app',
    measurementId: 'G-Z9SGMPKX10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4i4kKB696czvSbzla1sTHBZtfAdKEUjo',
    appId: '1:475073115193:android:53dd3ea803c01d76acc9e8',
    messagingSenderId: '475073115193',
    projectId: 'sih-learning-platform',
    storageBucket: 'sih-learning-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZklTRJWCvcdKCuGfq6F9C883dfAntyLU',
    appId: '1:475073115193:ios:9e9f83cb42f4929facc9e8',
    messagingSenderId: '475073115193',
    projectId: 'sih-learning-platform',
    storageBucket: 'sih-learning-platform.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZklTRJWCvcdKCuGfq6F9C883dfAntyLU',
    appId: '1:475073115193:ios:9e9f83cb42f4929facc9e8',
    messagingSenderId: '475073115193',
    projectId: 'sih-learning-platform',
    storageBucket: 'sih-learning-platform.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWw10Ql1PQNBleeY4hcDrQc9nrlQ68Zwg',
    appId: '1:475073115193:web:1b546c2229e64fbeacc9e8',
    messagingSenderId: '475073115193',
    projectId: 'sih-learning-platform',
    authDomain: 'sih-learning-platform.firebaseapp.com',
    storageBucket: 'sih-learning-platform.firebasestorage.app',
    measurementId: 'G-6Y7JVXFJET',
  );

}