name: firestore_seed_cli
description: A simple command-line app to seed Firestore
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^2.23.0
  firebase_auth: ^4.6.4
  cloud_firestore: ^6.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
